name: Continuous Integration

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: friendbotdb
          POSTGRES_USER: friendbotuser
          POSTGRES_PASSWORD: friendbotpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-application

    - name: Run Docker Compose to execute tests
      run: |
        docker-compose -f docker-compose.yml up --build --abort-on-container-exit

    - name: Push Docker images
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag my-application yourdockerhubusername/my-application:latest
        docker push yourdockerhubusername/my-application:latest
      

   